<?php

namespace Sctr\Greenrope\Api\Tests;

use Sctr\Greenrope\Api\Client;
use Sctr\Greenrope\Api\Endpoint\AbstractEndpoint;
use Sctr\Greenrope\Api\Model\Contact;
use Sctr\Greenrope\Api\Request\Contact\AddContactsRequest;
use Sctr\Greenrope\Api\Response\ApiAuthTokenResponse;
use Sctr\Greenrope\Api\Service\XmlSerializer;

class GeneralTest extends BaseTest
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testGetTokenSuccess()
    {
        $params =['email' => 'thomas@bang.com', 'password' => 'SctrApi5!', 'api_url' => 'https://api.stgi.net/api-xml'];

        $auth = new class(new Client($params)) extends AbstractEndpoint{
            public function getAuthToken()
            {
                $parameters = [
                    'email' => 'thomas@bang.com',
                    'password' => 'SctrApi5!',
                    'xml' => AbstractEndpoint::GET_AUTH_TOKEN_XML
                ];

                $response = $this->client->post('https://api.stgi.net/api-xml', [ 'form_params' => $parameters ]);

                /** @var ApiAuthTokenResponse $response */
                $response = $this->xmlConverter->deserializeXml($response->getBody(), ApiAuthTokenResponse::class);

                if ($response->getSuccess() && !empty($response->getResult())) {
                    return $response->getResult();
                } else {
                    throw new \Exception(sprintf("Authentication error: %s", $response->getErrorText()));
                }
            }
        };

        /** @var ApiAuthTokenResponse $result */
        $result = $auth->getAuthToken();

        $this->assertNotNull($result);
    }
}
